config/routes.rb
CGWorks::Application.routes.draw do
  
  match 'admin' => 'admin#index'
  match 'admin/update_scrapbook_display' => 'admin#update_scrapbook_display', :as => 'admin_update_scrapbook_display', :via => :post
  match 'admin/refresh_all_tweets' => 'admin#refresh_all_tweets', :as => 'admin_refresh_all_tweets', :via => :post
  match 'admin/refresh_tweet' => 'admin#refresh_tweet', :as => 'admin_refresh_tweet', :via => :post
  match 'archives' => 'scrapbook#archives'
  match 'archives/:archived_month' => 'scrapbook#archived_month', :as => 'archived_month'
  match ':id' => 'scrapbook#entry', :as => 'scrapbook_entry'
  root :to => 'application#index'
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # t.integer :tweet_id, :null => false
  # add_column :photos, :image_file_name, :string
  # add_column :photos, :image_content_type, :string
  # add_column :photos, :image_file_size, :integer
  # add_column :photos, :image_updated_at, :datetime
  
  belongs_to :tweet
  
  has_attached_file :image, :styles => { :small => "150x150>", :medium => "300x300>", :large => "600x600>" },
                    :url  => "/photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/photos/:id/:style/:basename.:extension"
  
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  # t.text :text
  # t.integer :twitter_id
  # t.boolean :is_retweet
  # t.text :media
  # t.text :raw_feed
  # t.text :hashtags
  # t.text :mentions
  # t.text :links
  # t.boolean :display, :default => true
  
  attr_accessible :twitter_id, :raw_feed, :text, :is_retweet, :posted_at, :media, :hashtags, :mentions, :links
  
  has_many :photos
  
  validates_uniqueness_of :twitter_id
  
  validates_presence_of :raw_feed
  
  after_create :get_media
  
  private
  
  def get_media
    for media in self.media.to_s.split(",") do
      file = Tempfile.new([self.twitter_id,".jpg"])
      file.binmode
      open(URI.parse("#{YAML::load(media)['source']}:large")) do |data|  
        file.write data.read
      end
      file.rewind
      Photo.create(:image => file, :tweet_id => self.id)
		end
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  http_basic_authenticate_with(:name => APP_CONFIG['admin_username'], :password => APP_CONFIG['admin_password'], :realm => APP_CONFIG['admin_realm']) if !Rails.env.development?
  
  skip_before_filter :tweets_by_month
  
  def index
    @tweets = Tweet.find(:all, :order => 'posted_at DESC')
  end
  
  def update_scrapbook_display
    tweet = Tweet.find(params[:tweet])
    tweet.display ? tweet.display = false : tweet.display = true
    tweet.save!
    render :nothing => true
  end
  
  def refresh_all_tweets
    twitter_poll
    redirect_to admin_path
  end
  
  def refresh_tweet
    repoll_tweet(params[:tweet])
    redirect_to admin_path(:anchor => "#entry_#{params[:tweet]}")
  end
  
  private
  
  def repoll_tweet(twitter_id)
    current_tweet = Tweet.find_by_twitter_id(twitter_id)
    new_data = Twitter.status(twitter_id, {:include_rts => true, :include_entities => true})
    current_tweet.photos.destroy_all
    current_tweet.update_attributes(  
                          :raw_feed => new_data.instance_variable_get('@attrs').to_yaml,
                          :text => new_data.text, 
                          :is_retweet => (new_data.retweeted_status ? true : false),
                          :posted_at => new_data.created_at,
                          :media => pull_media(new_data),
                          :hashtags => pull_hashtags(new_data),
                          :mentions => pull_mentions(new_data),
                          :links => pull_links(new_data))
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :need_scrapbook_update?
  before_filter :tweets_by_month
  
  def index
    @tweets = Tweet.find(:all, :conditions => ["display = ? AND posted_at >= ?", true , 2.months.ago], :order => 'posted_at DESC', :limit => 20)
    render :template => '/index'
  end
  
  private
  
  def tweets_by_month
    @show_archive = true
    @tweets_by_month = Tweet.find(:all, :order => "posted_at DESC", :conditions => ["display = ? AND posted_at >= ?", true, 1.year.ago]).group_by { |tweet| tweet.posted_at.strftime("%B %Y")}
  end
  
  def need_scrapbook_update?
  	if File.exists?("#{Rails.root.to_s}/tmp/cache/scrapbook_cache")
  		if last_scrapbook_upate < 1.hour.ago
  			File.open("#{Rails.root.to_s}/tmp/cache/scrapbook_cache", "w+") {|f| f.write(Time.now)}
  			twitter_poll
  		end
  	else
  		File.open("#{Rails.root.to_s}/tmp/cache/scrapbook_cache", "w+") {|f| f.write(Time.now)}
  		twitter_poll
  	end
  end

  def last_scrapbook_upate
  	Time.parse(File.read("#{Rails.root.to_s}/tmp/cache/scrapbook_cache"))
  end

  def twitter_poll
  	for new_tweet in Twitter.user_timeline('GriffithStudio', {:include_rts => true, :include_entities => true})
  		store_tweet(new_tweet)
  	end
  end

  def store_tweet(data)
  	tweet = Tweet.create( :twitter_id => data.id, 
                          :raw_feed => data.instance_variable_get('@attrs').to_yaml,
                          :text => data.text, 
                          :is_retweet => (data.retweeted_status ? true : false),
                          :posted_at => data.created_at,
                          :media => pull_media(data),
                          :hashtags => pull_hashtags(data),
                          :mentions => pull_mentions(data),
                          :links => pull_links(data))
  end

  def pull_media(data)
    if data.instance_variable_get('@attrs')['entities']['media']
      media = []
      for entity in data.instance_variable_get('@attrs')['entities']['media'] do
        media_hash = Hash['source', entity['media_url'], 'display', entity['url'], 'type', entity['type']]
        media << media_hash.to_yaml
      end
      return media.join(",")
    else
      return nil
    end
  end

  def pull_links(data)
    if data.instance_variable_get('@attrs')['entities']['urls']
      links = []
      for link in data.instance_variable_get('@attrs')['entities']['urls'] do
        link_hash = Hash['source', link['expanded_url'], 'display', link['url']] 
        links << link_hash.to_yaml
      end
      return links.join(",")
    end
  end

  def pull_hashtags(data)
    if data.instance_variable_get('@attrs')['entities']['hashtags']
      hashtags = []
      for hashtag in data.instance_variable_get('@attrs')['entities']['hashtags'] do
        hashtags << "##{hashtag['text']}"
      end
      return hashtags.join(",")
    else
      return nil
    end
  end

  def pull_mentions(data)
    if data.instance_variable_get('@attrs')['entities']['user_mentions']
      mentions = []
      for mention in data.instance_variable_get('@attrs')['entities']['user_mentions'] do
        mentions << "#{mention['screen_name']}"
      end
      return mentions.join(",")
    else
      return nil
    end
  end
  
end

app/controllers/scrapbook_controller.rb
class ScrapbookController < ApplicationController
  include ActionView::Helpers::TextHelper
  
  skip_before_filter :tweets_by_month, :only => [:archives]
  
  def archives
    @subtitle = "Archives"
    @archives = Tweet.find(:all, :conditions => {:display => true}, :order => "posted_at DESC").group_by { |tweet| tweet.posted_at.strftime("%B %Y")}
  end
  
  def archived_month
    @archived_month = Time.strptime(params[:archived_month], "%b-%Y")
    @subtitle = @archived_month.strftime("%B")
    @tweets = Tweet.find(:all, :conditions => { :display => true, :posted_at => @archived_month.beginning_of_month .. @archived_month.end_of_month }, :order => 'posted_at DESC')
  end
  
  def entry
    @tweet = Tweet.find_by_twitter_id(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  require "uri"
  
  def render_tweet(tweet)
		rendered_tweet = tweet.text

		for hashtag in tweet.hashtags.to_s.split(",")
			rendered_tweet.sub!("#{hashtag}", link_to(hashtag,"http://twitter.com/search/#{URI.escape(hashtag)}",:target => :blank))
		end

		for mention in tweet.mentions.to_s.split(",")
			rendered_tweet.sub!(/@#{mention}/i, link_to("@#{mention}","http://twitter.com/#{mention}",:target => :blank))
		end

		for link in tweet.links.to_s.split(",") do
			rendered_tweet.sub!((YAML::load(link)['display']), link_to((YAML::load(link)['source']),(YAML::load(link)['source']),:target => :blank))
		end

		for media in tweet.media.to_s.split(",") do
			rendered_tweet.sub!((YAML::load(media)['display']), "")
		end

		return raw rendered_tweet
	end
	
	def escaped_for_urls(url)
	  #CGI::encode(url)
	  return URI.escape(url, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
	end
	
end

app/views/admin/_entry.html.erb
<div class="entry" id="entry_<%= tweet.twitter_id -%>">
  <div class="contents">
    <div class="actions">
      <div class="visiblity">
        <%= check_box_tag "visibility", "visible", tweet.display, :class => "visiblity_checkbox", :onchange => "$.post('#{eval("admin_update_scrapbook_display_path(:tweet => #{tweet.id})")}')" %>
      </div>
      <!--
      <div class="refresh btn">
        <%= link_to "Refresh", "javascript:;", :onclick => "$.post('#{eval("admin_refresh_tweet_path(:tweet => #{tweet.twitter_id})")}')" %>
      </div>
      -->
    </div>
    <% for photo in tweet.photos do %>
  		<div class="media"><%= link_to image_tag(photo.image.url(:small)), photo.image.url(:original, false) %></div>
  	<% end %>
  	<div class="posted_at"><%= raw tweet.posted_at.strftime("<strong>%B #{tweet.posted_at.day.ordinalize}, %Y</strong> <span class='thin'>- %H:%M UTC</span>") %></div>
    <div class="tweet"><%= render_tweet(tweet) %></div>
    <div class="clear"></div>
  </div>
</div>

app/views/admin/index.html.erb
<% for tweet in @tweets do %>
	<%= render :partial => 'entry', :locals => {:tweet => tweet} %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  
  <title>CG Works | Admin</title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="header">
    <div class="contents">
      <h1><%= link_to "CG Works Admin", admin_path %></h1>
      <div class="refresh btn">
        <%= link_to "Refresh All", "javascript:;", :onclick => "$.post('#{eval("admin_refresh_all_tweets_path")}')" %>
      </div>
    </div>
  </div>
  
  <div id="main">
    <%= yield %>
  </div>
  
  <div id="footer">
    <div class="contents">
      <div class="copyright">&copy; Christopher Griffith Studio <%= Time.now.year -%></div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CG Works<%= "| #{@subtitle}" if @subtitle %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="CG Works<%= "| #{@subtitle}" if @subtitle %>">
  <meta name="author" content="Christopher Griffith Studio">
  <%= stylesheet_link_tag    "main", :media => "all" %>
  <%= javascript_include_tag "main" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if @show_archive %>
  <div id="archives">
    <ul>
      <% @tweets_by_month.each do |monthname, tweets| %>
      <li><%= link_to monthname, archived_month_path(monthname.parameterize) %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div id="content">
  <div id="header">
    <div class="logo">
      <%= link_to image_tag("logo.png", :alt => "CG WORKS", :title => "CG WORKS", :description => "Christopher Griffith Studio Works"), root_path %>
    </div>
    <h1>CG Works</h1>
    <%= raw("<h2>#{@subtitle}</h2>") if @subtitle %>
    <div class="clear"></div>
  </div>

  <div id="main">
    <%= yield %>
  </div>

  <div id="footer">
    <div class="contact">
      CHRISTOPHERGRIFFITH <span class="grey">STUDIO</span><br>
      The AUDITORIUM<br>
      121 WEST 27th ST<br>
      NEW YORK, NY<br>
      10001<br>
      T: +1.212.475.0007<br>
      <a href="mailto:studio@christophergriffith.com">studio@christophergriffith.com</a><br>
      <a href="http://www.christophergriffith.com">www.christophergriffith.com</a>
      
    </div>
    
    <div class="source_code">
      This app utilizes the Scrapbook gem for Rails. The source of both this app and the gem are released under the MIT license and available on <a href="http://github.com/GriffithStudio" target="_blank">Github</a>.
    </div>
    
    <div class="copyright">&copy;<%= Time.now.year -%> Christopher Griffith Studio</div>
  </div>
  
</div>

<%= render :partial => '/analytics' %>

</body>
</html>

app/views/scrapbook/_entry.html.erb
<li class="entry <%= 'retweet' if tweet.is_retweet -%>">
  <div class="posted_at"><%= raw tweet.posted_at.strftime("<strong>%B #{tweet.posted_at.day.ordinalize}, %Y</strong> <span class='thin'>- %H:%M UTC</span>") %></div>
	<% for photo in tweet.photos do %>
		<div class="media"><%= link_to image_tag(photo.image.url(:large)), photo.image.url(:original, false) %></div>
		<%= render :partial => '/scrapbook/social_links', :locals => {:tweet => tweet, :link_class => 'image', :photo => photo} %>
	<% end %>
	<div class="tweet <%= 'text' if tweet.photos.empty? %>"><%= render_tweet(tweet) %></div>
	<% if tweet.photos.empty? %>
	  <%= render :partial => '/scrapbook/social_links', :locals => {:tweet => tweet, :link_class => 'text', :photo => nil} %>
	<% end %>
	<div class="clear">
</li>

app/views/scrapbook/_social_links.html.erb
<ul class="social <%= link_class -%>">
  <li><%= link_to image_tag("link_icon.png"), scrapbook_entry_path(tweet.twitter_id), :title => "Link to this entry" %></li>
  <li><%= link_to image_tag("twitter_icon.png"), "https://twitter.com/share?url=#{scrapbook_entry_url(tweet.twitter_id)}&text=#{tweet.text}&count=horizontal", :title => "Share on Twitter", :target => "_blank" %></li>
  <li><%= link_to image_tag("pinterest_icon.png"), "http://pinterest.com/pin/create/button/?url=#{scrapbook_entry_url(tweet.twitter_id)}&media=#{photo ? photo.image.url(:large, false) : scrapbook_entry_url(tweet.twitter_id)}&description=#{tweet.text}", :title => "Share on Pinterest", :target => "_blank" %></li>
  <li><%= link_to image_tag("tumblr_icon.png"), "http://www.tumblr.com/share?v=3&u=#{escaped_for_urls(scrapbook_entry_url(tweet.twitter_id))}&t=#{tweet.text}", :title => "Share on Tumblr", :target => "_blank" %></li>
  <li><%= link_to image_tag("facebook_icon.png"), "http://www.facebook.com/share.php?u=#{escaped_for_urls(photo ? "#{root_url}#{photo.image.url(:large, false).gsub(/^\//, '')}" : scrapbook_entry_url(tweet.twitter_id))}", :title => "Share on Facebook", :target => "_blank" %></li>
</ul>

app/views/scrapbook/archived_month.html.erb
<ul id="tweets">
	<% for tweet in @tweets do %>
		<%= render :partial => 'scrapbook/entry', :locals => {:tweet => tweet} %>
	<% end %>
</ul>

app/views/scrapbook/archives.html.erb
<ul>
  <% @archives.each do |monthname, tweets| %>
  <li><%= link_to monthname, archived_month_path(monthname.parameterize) %> - <%= tweets.count -%> entries</li>
  <% end %>
</ul>

app/views/scrapbook/entry.html.erb
<ul id="tweets">
	<%= render :partial => 'scrapbook/entry', :locals => {:tweet => @tweet} %>
</ul>